In [2]:
import numpy as np
import pandas as pd

In [3]:
# task1
data = np.random.rand(4,4)
df = pd.DataFrame(data, columns=['col1','col2','col3','col4'])
df

       col1      col2      col3      col4
0  0.644380  0.369124  0.818703  0.013906
1  0.455904  0.174544  0.785540  0.478529
2  0.540927  0.789849  0.582714  0.020761
3  0.727150  0.888074  0.408943  0.495346

In [4]:
# task2
# renaming df - columns:
new_column_names = {'col1': 'Random value 1',
                    'col2': 'Random value 2',
                    'col3': 'Random value 3',
                    'col4': 'Random value 4'}
df = df.rename(columns=new_column_names)
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.644380        0.369124        0.818703        0.013906
1        0.455904        0.174544        0.785540        0.478529
2        0.540927        0.789849        0.582714        0.020761
3        0.727150        0.888074        0.408943        0.495346

In [5]:
# task3
# Find the descriptive statistics of the 'df' dataframe.
stats = df.describe()
stats

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.592090        0.555398        0.648975        0.252136
std          0.118518        0.339307        0.191018        0.271227
min          0.455904        0.174544        0.408943        0.013906
25%          0.519671        0.320479        0.539271        0.019047
50%          0.592653        0.579487        0.684127        0.249645
75%          0.665072        0.814405        0.793831        0.482733
max          0.727150        0.888074        0.818703        0.495346

In [6]:
# task4
# check for null values
null_values = df.isnull().sum()
print(null_values)

# Find data types
data_types = df.dtypes
print(data_types)

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64
Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [7]:
# task 5
# Display the 'Random value 2' & 'Random value 3' columns with location method and index location method
columns_loc = df.loc[:, ['Random value 2', 'Random value 3']]
print(columns_loc)

# Display columns using integer-based index location (iloc)
columns_iloc = df.iloc[:, [1, 2]]
print(columns_iloc)

   Random value 2  Random value 3
0        0.369124        0.818703
1        0.174544        0.785540
2        0.789849        0.582714
3        0.888074        0.408943
   Random value 2  Random value 3
0        0.369124        0.818703
1        0.174544        0.785540
2        0.789849        0.582714
3        0.888074        0.408943